factotum/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .models import User

urlpatterns = [
    path('', views.index, name='index'),
    path('profil/', views.profil, name="profil"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name="register"),
    path('professionnel/list/', views.liste_professionnel, name="liste_professionnel"),
    path('professionnel_service/new/<int:user_id>', views.ajout_service, name="ajout_service"),
    path('soumission/<int:pro_id>/<int:service_id>/new', views.ajout_soumission, name="ajout_soumission"),
    path('soumission/<int:soumission_id>/accepter', views.accepter_soumission, name="accepter_soumission"),
    path('soumission/<int:soumission_id>/terminer', views.terminer_soumission, name="terminer_soumission"),
    path('soumission/<int:soumission_id>/annuler', views.annuler_soumission, name="annuler_soumission"),
    path('soumission/<int:soumission_id>/noter', views.noter_soumission, name="noter_soumission"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tp1_VeilleuxPerras_Jerome/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from factotum import views

urlpatterns = [
    path('', include('factotum.urls')),
    path('admin/', admin.site.urls),
    path('factotum/', include("factotum.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

factotum/models.py
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import AbstractUser


class Service(models.Model):
    nom = models.CharField(max_length=255)

    def __str__(self):
        return '%s' % (self.nom,)


class User(AbstractUser):
    UTILISATEUR = 1
    PROFESSIONNEL = 2
    ROLE_CHOICES = (
        (UTILISATEUR, 'utilisateur'),
        (PROFESSIONNEL, 'professionnel'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=1)

    first_name = models.CharField(max_length=255, null=False)
    last_name = models.CharField(max_length=255, null=False)
    email = models.EmailField(null=False)

    adresse = models.CharField(max_length=255)
    code_Postal = models.CharField(max_length=6,
                                   validators=[RegexValidator("[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJ-NPRSTV-Z][ ]?|[-]?[0-9][ABCEGHJ-NPRSTV-Z][0-9]",
                                                              'Code postal invalide - assurez-vous que celui-ci soit en majuscule et qu\'il n\'ait aucune espace')],)
    description = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='media/images/', blank=True, null=True)
    Service = models.ForeignKey(Service, on_delete=models.CASCADE, null=True)
    telephone = models.CharField(max_length=10, default="", null=False, validators=[RegexValidator("^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$",
                                                            'Numéro de téléphone invalide')])

    def __str__(self):
        return '%s' % (self.id)


class ProfessionnelService(models.Model):
    taux_horaire = models.IntegerField()
    service_id = models.ForeignKey(Service, on_delete=models.CASCADE, null=False, default="")
    utilisateur_id = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="")

    def __str__(self):
        return '%s' % (self.utilisateur_id)


class Soumission(models.Model):
    date_planification = models.DateField(null=False)
    date_finis = models.DateField(null=True, blank=True)
    description = models.TextField(null=False)
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE, null=False, default="")
    id_service_Professionnel = models.ForeignKey(ProfessionnelService, on_delete=models.CASCADE, null=False, default="")
    note = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])

    EN_ATTENTE = 1
    ACCEPTEE = 2
    TERMINEE = 3
    ANNULEE = 4
    STATE_CHOICE = (
        (EN_ATTENTE, 'En Attente'),
        (ACCEPTEE, 'Accepté'),
        (TERMINEE, 'Terminé'),
        (ANNULEE, 'Annulé')
    )
    etat = models.PositiveSmallIntegerField(choices=STATE_CHOICE)

    def __str__(self):
        return '%s : %s : %s : %s : %s' % (self.id_service_Professionnel,
                                           self.utilisateur_id,
                                           self.date_planification,
                                           self.date_finis,
                                           self.note)

factotum/forms.py
from django import forms

from tp1_VeilleuxPerras_Jerome import settings
from .models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "password1",
                  "password2", "telephone", "code_Postal", "email", "adresse", "role", "avatar"]
        labels = {"username": "pseudo"}, {"password1": "mot de passe"}, \
            {"password2": "confirmation du mot de passe"}, {"first_name": "prénom"}, \
            {"last_name": "nom"}


class SearchProfessionnal(forms.Form):
    SERVICES = (
        (1, 'Charpentier'),
        (2, 'Électricien'),
        (3, 'Plombier'),
        (4, 'EntretienMénager'),
        (5, 'EntretienPaysager'),
    )
    services = forms.IntegerField()
    code_postal = forms.CharField(min_length=6, max_length=6, required=True)


class AjoutServiceProfessionnel(forms.Form):
    SERVICES = (
        (1, 'Charpentier'),
        (2, 'Électricien'),
        (3, 'Plombier'),
        (4, 'EntretienMénager'),
        (5, 'EntretienPaysager'),
    )
    services = forms.IntegerField()
    taux_horaire = forms.IntegerField(required=True)


class AjoutSoumission(forms.Form):
    date_planification = forms.DateField()
    description = forms.CharField(widget=forms.Textarea, required=True)

factotum/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import RegisterForm, SearchProfessionnal, AjoutServiceProfessionnel, AjoutSoumission
from .models import User, Soumission, ProfessionnelService, Service
from django.contrib import messages
from tp1_VeilleuxPerras_Jerome import settings
import urllib.request
import json


# Vue de départ, initialise la base sur quoi tout les templates seront redirigé
def index(request):
    return render(request, 'factotum/base.html')


# Vue pour la page de profil d'un utilisateur
@login_required(login_url='/accounts/login/')
def profil(request):
    soumissions = Soumission.objects.all()
    soumission = []
    for item in soumissions:
        if item.id_service_Professionnel.utilisateur_id.id == request.user.id:
            soumission.append(item)

    for item in soumissions:
        if item.utilisateur_id == request.user.id:
            soumission.append(item)

    soumissions_demande = Soumission.objects.filter(utilisateur_id=request.user.id)

    services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)

    return render(request, 'factotum/profil_details.html', {'soumissions': soumission,
                                                            'soumissionsDemande': soumissions_demande,
                                                            'user_services': services})


# Vue pour créer un nouveau compte
def register(request):
    if request.method == "POST":
        form = RegisterForm(data=request.POST, files=request.FILES)
        if form.data['email'] != "":
            adresse = User.objects.filter(email=form.data['email'])

            if len(adresse) != 0:
                messages.add_message(request, messages.INFO, 'Cette adresse est déjà utilisé')

        if form.is_valid() and request.FILES['avatar']:
            form.save()
            return redirect("login")

    else:
        form = RegisterForm()

    return render(request, "registration/register.html", {"form": form})


# Vue qui affiche la liste de professionnel à la suite d'une recherche
def liste_professionnel(request):
    list_pro = []
    api_key = settings.API_KEY
    allServices = Service.objects.all()

    if request.method == "POST":
        form = SearchProfessionnal(request.POST)
        a = request.POST['services']
        service = Service.objects.get(id=a)

        code_postal = request.POST['code_postal']

        if form.is_valid():
            servicesPro = ProfessionnelService.objects.filter(service_id=service)

            for pro in servicesPro:

                notes = Soumission.objects.filter(id_service_Professionnel=pro.utilisateur_id.id)
                total = 0
                for proNote in notes:
                    total = total + proNote.note

                res = urllib.request.urlopen('http://www.zipcodeapi.com/rest/v2/CA/' + api_key +
                                             '/distance.json/' + code_postal.replace(' ', '') +
                                             '/' + pro.utilisateur_id.code_Postal.replace(' ', '') + '/km')
                json_data = json.load(res)

                result = (
                    (pro, json_data['distance'], total)
                )

                list_pro.append(result)
                list_pro.sort(key=lambda a: a[1])

            return render(request, 'factotum/professionnel_list.html',
                          {'professionnels': list_pro})

    else:
        form = SearchProfessionnal()

    return render(request, 'factotum/recherche.html', {'form': form, 'services': allServices})


# Vue pour ajouter un service à un utilisateur professionnel
@login_required(login_url='/accounts/login/')
def ajout_service(request, user_id):
    allServices = Service.objects.all()
    if request.method == "POST":
        form = AjoutServiceProfessionnel(request.POST)
        a = request.POST['services']
        taux_horaire = request.POST['taux_horaire']

        if form.is_valid():
            service = Service.objects.get(id=a)
            user = User.objects.get(id=request.user.id)
            ProfessionnelService.objects.create(taux_horaire=taux_horaire, service_id=service,
                                                utilisateur_id=user)
            services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)
            return render(request, 'factotum/profil_details.html', {'user_services': services})

    else:
        form = AjoutServiceProfessionnel()

    return render(request, 'factotum/serviceProfessionnel_new.html', {'form': form, 'allServices': allServices})


# Vue pour créer une demande de soumission d'un utilisateur à un professionnel
@login_required(login_url='/accounts/login/')
def ajout_soumission(request, pro_id, service_id):
    if request.method == "POST":
        form = AjoutSoumission(request.POST)

        if form.is_valid():

            pro = ProfessionnelService.objects.get(utilisateur_id=pro_id, service_id=service_id)
            date = form.cleaned_data['date_planification']
            description = form.cleaned_data['description']

            Soumission.objects.create(description=description, etat=1,
                                      date_planification=date, id_service_Professionnel=pro,
                                      utilisateur_id=request.user.id, note=0)

        services = Service.objects.all()
        return render(request, 'factotum/recherche.html', {'services': services})

    else:
        form = AjoutSoumission()

    pro = ProfessionnelService.objects.get(utilisateur_id=pro_id, service_id=service_id)

    index = (
        (pro.utilisateur_id.id, service_id)
    )

    return render(request, 'factotum/soumission_new.html', {'form': form, 'pro': index})


# Vue pour changer l'état d'une soumission à 'Accepter'
def accepter_soumission(request, soumission_id):
    soumission = Soumission.objects.get(id=soumission_id)
    soumission.etat = 2
    soumission.save()

    soumissions = Soumission.objects.all()
    soumission = []
    for item in soumissions:
        if item.id_service_Professionnel.utilisateur_id.id == request.user.id:
            soumission.append(item)

    soumissionsDemande = Soumission.objects.filter(utilisateur_id=request.user.id)

    services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)

    return render(request, 'factotum/profil_details.html', {'soumissions': soumission,
                                                            'soumissionsDemande': soumissionsDemande,
                                                            'user_services': services})


# Vue pour changer l'état d'une soumission à 'Terminer'
def terminer_soumission(request, soumission_id):
    soumission = Soumission.objects.get(id=soumission_id)
    soumission.etat = 3
    soumission.date_finis = datetime.date.today()
    soumission.save()

    soumissions = Soumission.objects.all()
    soumission = []
    for item in soumissions:
        if item.id_service_Professionnel.utilisateur_id.id == request.user.id:
            soumission.append(item)

    soumissionsDemande = Soumission.objects.filter(utilisateur_id=request.user.id)

    services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)

    return render(request, 'factotum/profil_details.html', {'soumissions': soumission,
                                                            'soumissionsDemande': soumissionsDemande,
                                                            'user_services': services})


# Vue pour changer l'état d'une soumission à Annuler
def annuler_soumission(request, soumission_id):
    soumission = Soumission.objects.get(id=soumission_id)
    soumission.etat = 4
    soumission.save()

    soumissions = Soumission.objects.all()
    soumission = []
    for item in soumissions:
        if item.id_service_Professionnel.utilisateur_id.id == request.user.id:
            soumission.append(item)

    soumissionsDemande = Soumission.objects.filter(utilisateur_id=request.user.id)

    services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)

    return render(request, 'factotum/profil_details.html', {'soumissions': soumission,
                                                            'soumissionsDemande': soumissionsDemande,
                                                            'user_services': services})

# Vue pour noter une soumission lorsque terminé (incomplète)
def noter_soumission(request, soumission_id):
    soumission = Soumission.objects.get(id=soumission_id)
    soumission.note = soumission.note + 1
    soumission.save()

    soumissions = Soumission.objects.all()
    soumission = []
    for item in soumissions:
        if item.id_service_Professionnel.utilisateur_id.id == request.user.id:
            soumission.append(item)

    soumissionsDemande = Soumission.objects.filter(utilisateur_id=request.user.id)

    services = ProfessionnelService.objects.filter(utilisateur_id=request.user.id)

    return render(request, 'factotum/profil_details.html', {'soumissions': soumission,
                                                            'soumissionsDemande': soumissionsDemande,
                                                            'user_services': services})

factotum/templates/factotum/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'factotum/css/bootstrap.min.css' %}">
</head>
<body>
<header>
    <div class="d-flex border-bottom mt-2 ml-2 justify-content-between">
        <a href="{% url "index" %}">
            <img src="{% static "factotum/img/logo.png" %}">
        </a>

        <div class="d-flex">

            {% if not user.is_authenticated %}
                <a href="{% url "login" %}" class="align-self-center">
                    <h5 class="text-dark pr-5">Se connecter</h5>
                </a>
            {% else %}
                <a href="{% url "logout" %}" class="align-self-center">
                    <h5 class="text-dark pr-5">Se déconnecter</h5>
                </a>
            {% endif %}

            {% if user.is_authenticated %}
                <a href="{% url "profil" %}" class="align-self-center">
                    <h5 class="text-dark pr-5">Profil de {{ user.username }}</h5>
                </a>
            {% endif %}
        </div>

    </div>
</header>

<main>
    <div class="d-flex flex-column mb-2 bg-dark border border-secondary">
        <h2 class="d-flex justify-content-center text-white pt-3 pb-3">Prendre soin de votre maison, en toute
            simplicité!</h2>
        <div class="d-flex justify-content-center mb-2">
            <a href="{% url "liste_professionnel" %}" class="button btn-secondary rounded p-2 ">Commencer une
                recherche</a>
        </div>
    </div>

    {% block content %}

    {% endblock %}
</main>

<footer>

</footer>
</body>
</html>

factotum/templates/factotum/professionnel_list.html
{% extends "factotum/base.html" %}

{% block content %}
    <div class="d-flex w-100 col-10 offset-1">
        {% for professionnel in professionnels %}
            <div class="d-flex border border-secondary bg-light p-3 w-50 col-6 m-2">
                <img src="{{ professionnel.0.utilisateur_id.avatar.url }}" class="img-fluid rounded-circle w-25">
                <div class="d-flex w-75 border-left border-secondary ml-3">
                    <div class="d-flex pl-3 w-100 justify-content-between">
                        <div class="d-flex flex-column">
                            <h4>{{ professionnel.0.utilisateur_id.first_name }} {{ professionnel.0.utilisateur_id.last_name }}</h4>
                            <h5>{{ professionnel.2 }}</h5>
                            <h5>{{ professionnel.1 }} km</h5>
                            <h5>Taux - {{ professionnel.0.taux_horaire }}$ / heure</h5>
                        </div>
                        <div>
                            <a href="{% url "ajout_soumission" professionnel.0.utilisateur_id.id professionnel.0.service_id.id %}"
                               class="button btn-secondary rounded p-2">Voir Profile</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

factotum/templates/factotum/profil_details.html
{% extends "factotum/base.html" %}

{% block content %}
    <div class="d-flex w-100 border-top border-secondary">
        <div class="d-flex bg-light w-25 justify-content-center align-items-center">
            <img src="{{ user.avatar.url }}" class="img-fluid rounded-circle p-4">
        </div>
        <div class="bg-light w-75 d-flex w-100">
            <div class="bg-light w-25">
                <h4 class="w-100 border-bottom pt-1 pb-1">Info du compte</h4>
                {% if user.role == 2 %}
                    <p>*note</p>
                {% endif %}
                <p>Pseudo - {{ user.username }}</p>
                <p>Nom - {{ user.first_name }} {{ user.last_name }}</p>

            </div>
            <div class="bg-light w-25">
                <h4 class="w-100 border-bottom pt-1 pb-1">Me Contacter</h4>
                <p>Email - {{ user.email }}</p>
                <p>Téléphone - {{ user.telephone }}</p>
                <p>Adresse - {{ user.adresse }}</p>
                <p>Code postal - {{ user.code_Postal }}</p>
            </div>
            {% if user.role == 2 %}
                <div class="bg-light w-50 pl-2 border-left">
                    <div class="d-flex flex-column">
                        <div class="d-flex">
                            <h4 class="pt-1 pb-1">Vos services actuels</h4>
                            <a href="{% url "ajout_service" user.id %}"
                               class="button btn-secondary rounded p-2 ml-4 mt-2">
                                Ajouter un service</a>
                        </div>
                        <div class="">
                            {% for service in user_services %}
                                <p>{{ service.service_id.nom }}</p>
                            {% endfor %}
                        </div>

                    </div>

                </div>
            {% endif %}

        </div>
    </div>

    <table class="bg-light mt-4 w-100">
        <thead class="border-bottom border-secondary w-100">
        <tr class="d-flex flex-column">
            <th><h4>Vos Demandes Personnelles</h4></th>
        </tr>
        </thead>
        <tbody>
        <tr class="d-flex flex-column">
        <tr class="border-bottom border-secondary">
            <td class="border-left border-secondary">Date planification</td>
            <td class="border-left border-secondary">Date terminé</td>
            <td class="border-left border-secondary">Prénom</td>
            <td class="border-left border-secondary">Nom</td>
            <td class="border-left border-secondary">Téléphone</td>
            <td class="border-left border-secondary">Service</td>
            <td class="border-left border-secondary">Description</td>
            <td class="border-left border-secondary">État</td>
        </tr>
        {% for soumission in soumissionsDemande %}
            <tr class="border-bottom border-secondary">
                <td class="p-2 border-left">{{ soumission.date_planification }}</td>
                <td class="p-2 border-left">
                    {% if soumission.date_finis == None %}
                        -----
                    {% else %}
                        {{ soumission.date_finis }}
                    {% endif %}
                </td>
                <td class="p-2 border-left">{{ soumission.id_service_Professionnel.utilisateur_id.first_name }}</td>
                <td class="p-2 border-left">{{ soumission.id_service_Professionnel.utilisateur_id.last_name }}</td>
                <td class="p-2 border-left">{{ soumission.id_service_Professionnel.utilisateur_id.telephone }}</td>
                <td class="p-2 border-left">{{ soumission.id_service_Professionnel.service_id.nom }}</td>
                <td class="p-2 border-left">{{ soumission.description }}</td>
                <td class="p-2 border-left border-right">{{ soumission.get_etat_display }}</td>
                <td class="p-2">
                    {% if soumission.date_finis != None %}
                        <a href="{% url "noter_soumission" soumission.id %}"
                            class="button btn-primary border border-secondary p-1 rounded">Noter</a>
                    {% else %}
                        <a href="{% url "annuler_soumission" soumission.id %}"
                            class="button btn-primary border border-secondary p-1 rounded">Annuler</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tr>

        </tbody>
    </table>

    {% if user.role == 2 %}
        <table class="bg-light mt-3 w-100">
            <thead class="border-bottom border-secondary w-100">
            <tr class="d-flex flex-column">
                <th><h4>Vos Demandes de Soumissions</h4></th>
            </tr>
            </thead>
            <tbody>
            <tr class="d-flex flex-column">
            <tr class="border-bottom border-secondary">
                <td class="border-left border-secondary">Date planification</td>
                <td class="border-left border-secondary">Date terminé</td>
                <td class="border-left border-secondary">Prénom</td>
                <td class="border-left border-secondary">Nom</td>
                <td class="border-left border-secondary">Téléphone</td>
                <td class="border-left border-secondary">Service</td>
                <td class="border-left border-secondary">Description</td>
                <td class="border-left border-secondary">État</td>
            </tr>
            {% for soumission in soumissions %}
                <tr class="border-bottom border-secondary">
                    <td class="p-2 border-left">{{ soumission.date_planification }}</td>
                    <td class="p-2 border-left">
                        {% if soumission.date_finis == None %}
                            -----
                        {% else %}
                            {{ soumission.date_finis }}
                        {% endif %}
                    </td>
                    <td class="p-2 border-left">{{ soumission.utilisateur.first_name }}</td>
                    <td class="p-2 border-left">{{ soumission.utilisateur.last_name }}</td>
                    <td class="p-2 border-left">{{ soumission.utilisateur.telephone }}</td>
                    <td class="p-2 border-left">{{ soumission.id_service_Professionnel.service_id.nom }}</td>
                    <td class="p-2 border-left">{{ soumission.description }}</td>
                    <td class="p-2 border-left border-right">{{ soumission.get_etat_display }}</td>
                    <td class="p-2 d-flex justify-content-around">
                        {% if soumission.etat != 4 %}
                            {% if soumission.etat != 3 %}
                                {% if soumission.etat != 2 %}
                                    <a href="{% url "accepter_soumission" soumission.id %}"
                                       class="button btn-primary border border-secondary p-1 rounded">Accepter</a>
                                {% endif %}
                                <a href="{% url "terminer_soumission" soumission.id %}"
                                    class="button btn-primary border border-secondary p-1 rounded">Terminer</a>
                                <a href="{% url "annuler_soumission" soumission.id %}"
                                    class="button btn-primary border border-secondary p-1 rounded">Annuler</a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tr>
            </tbody>
        </table>
    {% endif %}

{% endblock %}

factotum/templates/factotum/profil_details_asVisitor.html
{% extends "factotum/base.html" %}

{% block content %}
{% endblock %}

factotum/templates/factotum/recherche.html
{% extends "factotum/base.html" %}

{% block content %}
    <form method="POST" class="d-flex bg-light p-3 mb-2 border border-secondary"
          action="{% url "liste_professionnel" %}">
        {% csrf_token %}

        <div class="d-flex align-items-end w-100 justify-content-center">
            <div class="d-flex flex-column">
                <div>
                    <label for="services">Choisissez un service</label>
                </div>
                <div>
                    <select name="services" id="services" required>
                        {% for service in services %}
                            <option value="{{ service.id }}">{{ service.nom }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="d-flex flex-column ml-5 mr-5">
                <div>
                    <label for="code_postal">Code Postal</label>
                </div>
                <div>
                    <input type="text" name="code_postal" id="code_postal" required>
                </div>
                <div class="text-danger">
                    {{ form.errors }}
                </div>
            </div>

            <div>
                <input type="submit" value="Soumettre">
            </div>
        </div>
    </form>
{% endblock %}

factotum/templates/factotum/serviceProfessionnel_new.html
{% extends "factotum/base.html" %}

{% block content %}
    <form method="POST" class="d-flex bg-light p-3 mb-2 border border-secondary"
          action="{% url "ajout_service" user.id %}">
        {% csrf_token %}
        <div class="d-flex flex-column w-100">
            <div class="d-flex w-100 justify-content-center">
                <div class="d-flex flex-column mr-5">
                    <div>
                        <label for="services">Choisissez un service</label>
                    </div>
                    <div>
                        <select name="services" id="services" required>
                            {% for service in allServices %}
                                <option value="{{ service.id }}">{{ service.nom }}</option>
                            {% endfor %}
                        </select>

                    </div>
                </div>

                <div class="d-flex flex-column">
                    <div>
                        <label for="taux_horaire">Taux Horaire</label>
                    </div>
                    <div>
                        {{ form.taux_horaire }}
                    </div>
                    <div class="text-danger">
                        {{ form.errors }}
                    </div>
                </div>
            </div>

            <div class="d-flex justify-content-center mt-3">
                <input type="submit" value="Soumettre">
            </div>
        </div>
    </form>

{% endblock %}

factotum/templates/factotum/soumission_new.html
{% extends "factotum/base.html" %}

{% block content %}
    <form method="POST" class="d-flex bg-light p-3 mb-2 border border-secondary"
          action="{% url "ajout_soumission" pro.0 pro.1 %}">
    {# pro #}
        {% csrf_token %}

        <div class="d-flex flex-column w-100">
            <div class="d-flex w-100 justify-content-center">
                <div class="d-flex flex-column">
                    <div>
                        <label for="date_planification">Date de planification</label>
                    </div>
                    <div>
                        <input type="date" id="date_planification" name="date_planification">
                    </div>
                    <div>
                        {{ form.errors }}
                    </div>
                </div>

                <div class="ml-5">
                    <div>
                        <label for="description">Description</label>
                    </div>
                    <div>
                <textarea id="description" name="description" rows="3" cols="50">

                </textarea>
                    </div>
                    <div class="text-danger">
                        {{ form.errors }}
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <input type="submit" value="Soumettre">
            </div>
        </div>

    </form>
{% endblock %}